#!/bin/sh

# function
download_file_code () {
cd ~
wget --no-check-certificate -q "https://raw.githubusercontent.com/itvn9online/Ethereum-private-key-scan/main/"$1 -O "/root/njs/e/"$1
}

# cleanup
cd ~
sudo rm -rf ~/njs/e/scan.*

# download
download_file_code "scan.js"
download_file_code "config.js"
download_file_code "functions.js"

# chmod
cd ~
sudo chmod +x ~/njs/e/scan.js

# run
cd ~/njs/e
node scan
