#!/bin/sh

# install and run in centos
cd ~
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
sudo yum -y install nodejs
node --version

# install plugin
cd ~

mkdir -p /root/njs/e/writable/logs
chmod 777 /root/njs/e/writable/logs

mkdir -p /root/njs/e/writable
chmod 777 /root/njs/e/writable

mkdir -p /root/njs/e
chmod 777 /root/njs/e

cd /root/njs/e
npm i ethers
npm i request
sleep 2

npm cache clean
sleep 2

# scan
cd ~
bash <( curl -k https://raw.githubusercontent.com/itvn9online/Ethereum-private-key-scan/main/scanonly )
