#!/bin/sh

# install and run in centos
cd ~
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
sudo yum -y install nodejs
sudo npm install -g npm
node --version

# install plugin
cd ~

mkdir -p /njs/e/writable/logs
chmod 777 /njs/e/writable/logs

mkdir -p /njs/e/writable
chmod 777 /njs/e/writable

mkdir -p /njs/e
chmod 777 /njs/e

cd /njs/e
npm i coinkey
npm i request
sleep 2

npm cache clean
sleep 2

# scan
cd ~
bash <( curl -k https://raw.githubusercontent.com/itvn9online/Bitcoin-private-key-scan/main/scanonly-aws )
