#!/bin/sh

# install and run in centos
cd ~
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
sudo yum -y install nodejs
sudo npm install -g npm
node --version

# install plugin
cd ~

sudo mkdir -p ~/njs/e/writable/logs
sudo chmod 777 ~/njs/e/writable/logs

sudo mkdir -p ~/njs/e/writable
sudo chmod 777 ~/njs/e/writable

sudo mkdir -p ~/njs/e
sudo chmod 777 ~/njs/e

cd ~/njs/e
sudo npm i ethers
sudo npm i request
sleep 2

sudo npm cache clean
sleep 2

# scan
cd ~
bash <( curl -k https://raw.githubusercontent.com/itvn9online/Ethereum-private-key-scan/main/scanonly-aws )
